### ISSUE TITLE
No longer showing One-Tap sign up when running locally

### ISSUE THREAD

**Issue by WestonThayer** [TMSCH/GoogleYoloIframed#1]
1. Clone this repo
2. Run `python -m SimpleHTTPServer 8080` in the repo's root
3. Visit http://localhost:8080/

ACTUAL: Blank page
EXPECTED: Google One-tap sign up should show

**Comment by adriancast** [comment]
I am also having this problem, but I think it also happens following the oficial documentation. Here is the error displayed in the console.
![image](https://user-images.githubusercontent.com/17761956/45076808-ad886380-b0eb-11e8-915c-f462a6410164.png)
I also tried to set the timeout to 5s without success

I think this problem is Google related

**Comment by TMSCH** [comment]
Can you look at the network tab for requests to a google.com domain? Is there any failed request? Any other errors in the console?

**Comment by WestonThayer** [comment]
Yes, the `GET` request to `https://smartlock.google.com/iframe/request` fails. Google returns a `403`.

Here is the full link address with query params:

```
https://smartlock.google.com/iframe/request?client=http%3A%2F%2Flocalhost%3A8080&id=6d5ab3b62377329f921cce86564628dd901b226a7a38d36c70964dec2d27e163&renderMode=navPopout&preloadRequest=%7B%22type%22%3A%22hint%22%2C%22options%22%3A%7B%22supportedAuthMethods%22%3A%5B%22openyolo%3A%2F%2Fid-and-password%22%2C%22https%3A%2F%2Faccounts.google.com%22%5D%2C%22supportedIdTokenProviders%22%3A%5B%7B%22uri%22%3A%22https%3A%2F%2Faccounts.google.com%22%2C%22clientId%22%3A%22511828570984-dhnshqcpegee66hgnp754dupe8sbas18.apps.googleusercontent.com%22%7D%5D%7D%7D
```

@TMSCH are you able to repro this locally? I suspect this is due to the recently implemented whitelist.

**Comment by TMSCH** [comment]
I can repro the issue locally. This seems indeed due to the recent whitelist. As it is run within an IFrame, it is likely to forbid using one tap. I would suggest not using an IFrame (this should only be used in very specific and rare cases) and apply to be white listed.

Closing as unrelated to this sample app.
